name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  init:
    name: Initialize
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  build:
    name: Build
    needs: ["init"]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Zip Extension
        run: zip -qq -r pingpe-overview.zip . -x "*.git*" "dist/*"

      - name: Publish Firefox
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: pingpe-overview@arash-hatami.ir
          jwt-issuer: ${{ secrets.FIREFOX_API_KEY }}
          jwt-secret: ${{ secrets.FIREFOX_API_SECRET }}
          xpi-path: pingpe-overview.zip
          license: MIT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          make_latest: true
          files: pingpe-overview.zip
