name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  init:
    name: Initialize
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  build:
    name: Build
    needs: ["init"]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Zip Extension
        run: zip -qq -r pingpe-overview.zip * --exclude '*.git*'
        working-directory: dist/

      - name: Publish Firefox
        uses: maoserr/firefox_extension_publish@v1.0.4
        with:
          firefox_extension_id: pingpe-overview@arash-hatami.ir
          api_key: ${{ secrets.FIREFOX_API_KEY }}
          api_secret: ${{ secrets.FIREFOX_API_SECRET }}
          file: dist/pingpe-overview.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          make_latest: true
          files: dist/pingpe-overview.zip
